use crate::models::CoinInfoDto;

pub fn describe_coin(symbol: &str) -> String {
    get_coin_info(symbol, &[]).summary
}

pub fn get_coin_info(symbol: &str, listed_exchanges: &[String]) -> CoinInfoDto {
    let listed = listed_exchanges.to_vec();
    match symbol {
        "BTC/USDT" => curated(
            "Bitcoin",
            "BTC",
            "The original crypto reserve asset with the deepest cross-exchange liquidity and the cleanest macro sensitivity.",
            Some("https://bitcoin.org"),
            Some("https://bitcoin.org/bitcoin.pdf"),
            Some("https://mempool.space"),
            "Bitcoin",
            Some("$1.3T"),
            Some("$1.3T"),
            Some("19.7M BTC"),
            Some("19.7M BTC"),
            Some("21.0M BTC"),
            Some("$32B"),
            &["Macro Sensitive", "Crowded Positioning"],
            Some("https://github.com/bitcoin/bitcoin"),
            listed,
        ),
        "ETH/USDT" => curated(
            "Ethereum",
            "ETH",
            "The settlement layer for the largest onchain application ecosystem, with strong spot depth and catalyst risk around upgrades and ETF flows.",
            Some("https://ethereum.org"),
            Some("https://ethereum.org/en/whitepaper/"),
            Some("https://etherscan.io"),
            "Ethereum",
            Some("$430B"),
            Some("$430B"),
            Some("120.1M ETH"),
            Some("120.1M ETH"),
            None,
            Some("$18B"),
            &["Event Sensitive", "High Derivatives Usage"],
            Some("https://github.com/ethereum"),
            listed,
        ),
        "SOL/USDT" => curated(
            "Solana",
            "SOL",
            "A high-beta smart-contract asset with fast throughput, strong meme flow sensitivity, and sharper intraday volatility than BTC or ETH.",
            Some("https://solana.com"),
            None,
            Some("https://solscan.io"),
            "Solana",
            Some("$70B"),
            Some("$84B"),
            Some("468M SOL"),
            Some("597M SOL"),
            None,
            Some("$6B"),
            &["High Beta", "Narrative Driven"],
            Some("https://github.com/solana-labs/solana"),
            listed,
        ),
        "DOGE/USDT" => curated(
            "Dogecoin",
            "DOGE",
            "A meme-led large-cap coin that can sustain strong liquidity, but usually trades on sentiment bursts rather than structural catalysts.",
            Some("https://dogecoin.com"),
            None,
            Some("https://dogechain.info"),
            "Dogecoin",
            Some("$22B"),
            Some("$22B"),
            Some("144.6B DOGE"),
            Some("144.6B DOGE"),
            None,
            Some("$2B"),
            &["Meme", "Headline Sensitive"],
            Some("https://github.com/dogecoin/dogecoin"),
            listed,
        ),
        "XRP/USDT" => curated(
            "XRP",
            "XRP",
            "A payments-focused large-cap token whose price can react sharply to regulatory headlines and exchange relisting momentum.",
            Some("https://xrpl.org"),
            None,
            Some("https://livenet.xrpl.org"),
            "XRP Ledger",
            Some("$34B"),
            Some("$59B"),
            Some("55.8B XRP"),
            Some("99.9B XRP"),
            Some("100B XRP"),
            Some("$2B"),
            &["Regulatory Risk", "Headline Sensitive"],
            Some("https://github.com/XRPLF"),
            listed,
        ),
        "ADA/USDT" => curated(
            "Cardano",
            "ADA",
            "A slower-moving large-cap smart-contract token that tends to need clear ecosystem or governance catalysts to escape range conditions.",
            Some("https://cardano.org"),
            None,
            Some("https://cardanoscan.io"),
            "Cardano",
            Some("$16B"),
            Some("$20B"),
            Some("35.3B ADA"),
            Some("45B ADA"),
            Some("45B ADA"),
            Some("$650M"),
            &["Slow Catalyst Cycle", "Lower Momentum"],
            Some("https://github.com/input-output-hk"),
            listed,
        ),
        "BNB/USDT" => curated(
            "BNB",
            "BNB",
            "An exchange-linked large-cap asset with persistent utility, but elevated venue concentration and policy sensitivity.",
            Some("https://www.bnbchain.org"),
            None,
            Some("https://bscscan.com"),
            "BNB Chain",
            Some("$85B"),
            Some("$85B"),
            Some("145.9M BNB"),
            Some("145.9M BNB"),
            Some("200M BNB"),
            Some("$1.7B"),
            &["Venue Concentration", "Policy Sensitive"],
            Some("https://github.com/bnb-chain"),
            listed,
        ),
        "AVAX/USDT" => curated(
            "Avalanche",
            "AVAX",
            "A smart-contract beta asset with periodic narrative rotations tied to gaming, subnet, and institutional tokenization themes.",
            Some("https://www.avax.network"),
            None,
            Some("https://snowtrace.io"),
            "Avalanche",
            Some("$14B"),
            Some("$18B"),
            Some("389M AVAX"),
            Some("450M AVAX"),
            Some("720M AVAX"),
            Some("$520M"),
            &["High Beta", "Narrative Rotation"],
            Some("https://github.com/ava-labs"),
            listed,
        ),
        "LINK/USDT" => curated(
            "Chainlink",
            "LINK",
            "A blue-chip oracle token that often trades on ecosystem integration flow and tends to move cleaner than lower-liquidity altcoins.",
            Some("https://chain.link"),
            Some("https://chain.link/whitepaper"),
            Some("https://etherscan.io/token/0x514910771AF9Ca656af840dff83E8264EcF986CA"),
            "Ethereum",
            Some("$10B"),
            Some("$16B"),
            Some("608M LINK"),
            Some("1B LINK"),
            Some("1B LINK"),
            Some("$420M"),
            &["Unlock Overhang", "Oracle Narrative"],
            Some("https://github.com/smartcontractkit"),
            listed,
        ),
        "SUI/USDT" => curated(
            "Sui",
            "SUI",
            "A faster-moving L1 beta asset with improving liquidity but ongoing unlock and sentiment risk around ecosystem adoption.",
            Some("https://sui.io"),
            None,
            Some("https://suivision.xyz"),
            "Sui",
            Some("$4B"),
            Some("$12B"),
            Some("3.0B SUI"),
            Some("10B SUI"),
            Some("10B SUI"),
            Some("$900M"),
            &["Unlock Pressure", "High Beta"],
            Some("https://github.com/MystenLabs"),
            listed,
        ),
        "TRX/USDT" => curated(
            "TRON",
            "TRX",
            "A payments and stablecoin-heavy network token that usually trades with lower beta than meme-heavy altcoins but remains venue-flow sensitive.",
            Some("https://trondao.org"),
            None,
            Some("https://tronscan.org"),
            "TRON",
            Some("$11B"),
            Some("$11B"),
            Some("87.7B TRX"),
            Some("87.7B TRX"),
            None,
            Some("$450M"),
            &["Exchange Flow Sensitive", "Stablecoin Proxy"],
            Some("https://github.com/tronprotocol"),
            listed,
        ),
        "TON/USDT" => curated(
            "Toncoin",
            "TON",
            "A consumer-distribution-linked L1 token with strong headline beta to Telegram ecosystem developments and liquidity bursts.",
            Some("https://ton.org"),
            None,
            Some("https://tonviewer.com"),
            "TON",
            Some("$17B"),
            Some("$27B"),
            Some("2.5B TON"),
            Some("5.1B TON"),
            Some("5.1B TON"),
            Some("$350M"),
            &["Headline Sensitive", "Ecosystem Concentration"],
            Some("https://github.com/ton-blockchain"),
            listed,
        ),
        _ => fallback(symbol, listed),
    }
}

fn curated(
    name: &str,
    symbol: &str,
    summary: &str,
    website: Option<&str>,
    whitepaper: Option<&str>,
    explorer: Option<&str>,
    ecosystem: &str,
    market_cap: Option<&str>,
    fdv: Option<&str>,
    circulating_supply: Option<&str>,
    total_supply: Option<&str>,
    max_supply: Option<&str>,
    volume_24h: Option<&str>,
    risk_tags: &[&str],
    github: Option<&str>,
    listed_exchanges: Vec<String>,
) -> CoinInfoDto {
    CoinInfoDto {
        name: name.into(),
        symbol: symbol.into(),
        summary: summary.into(),
        website: website.map(str::to_string),
        whitepaper: whitepaper.map(str::to_string),
        explorer: explorer.map(str::to_string),
        ecosystem: ecosystem.into(),
        market_cap: market_cap.map(str::to_string),
        fdv: fdv.map(str::to_string),
        circulating_supply: circulating_supply.map(str::to_string),
        total_supply: total_supply.map(str::to_string),
        max_supply: max_supply.map(str::to_string),
        volume_24h: volume_24h.map(str::to_string),
        listed_exchanges,
        risk_tags: risk_tags.iter().map(|item| (*item).to_string()).collect(),
        github: github.map(str::to_string),
    }
}

fn fallback(symbol: &str, listed_exchanges: Vec<String>) -> CoinInfoDto {
    let asset = symbol.split('/').next().unwrap_or(symbol);
    CoinInfoDto {
        name: asset.to_string(),
        symbol: asset.to_string(),
        summary: "Curated fundamentals are not available for this pair yet, but live venue coverage and market structure data are still active.".into(),
        website: None,
        whitepaper: None,
        explorer: None,
        ecosystem: "Coverage Pending".into(),
        market_cap: None,
        fdv: None,
        circulating_supply: None,
        total_supply: None,
        max_supply: None,
        volume_24h: None,
        listed_exchanges,
        risk_tags: vec!["Curated Coverage Pending".into()],
        github: None,
    }
}
